# Generated by Django 5.2.3 on 2025-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to='offers/%Y/%m/%d/'),
        ),
    ]
